### ISSUE TITLE
Syntax of make command incorrect

### ISSUE THREAD

**Issue by BdT141** [Alex079/vscode-avr-helper#11]
**Hi,**

**I ran the initial setup and tried to build, but I got the following error:**

_> Executing task: make -fc:\Users\brand\Desktop\AVR_TEST\.vscode\avr.targets.mk build <

===== Making .vscode/avr.build/obj/main.cpp.o

mkdir -p .vscode/avr.build/obj
The syntax of the command is incorrect.
make: *** [.vscode/avr.build/obj/main.cpp.o] Error 1
The terminal process "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command make -fc:\Users\brand\Desktop\AVR_TEST\.vscode\avr.targets.mk build" terminated with exit code: 1._

**My properties.mk file contains:**

_AVR.source.compiler = C:\Program Files (x86)\Atmel\Studio\7.0\toolchain\avr8\avr8-gnu-toolchain\bin\avr-gcc.exe
AVR.source.libraries = 
AVR.device.type = atmega328p
AVR.device.frequency = 16000000UL_

I'm working on Windows 10 with VS Code 1.55.2

I think the mkdir command doesn't like that the dir path contains forward slashes instead of backslashes. The make seems to be failing here:

_$(A.output.dir)/obj/%.cpp.o : %.cpp
	mkdir -p $(@D)
	$(info ===== Making $@)
	$(E.compile) $< -o $@
	$(info )_

**Comment by Alex079** [comment]
Hello!

I could reproduce the error, but in my case it's always cmd instead of powershell. Running mkdir with plain powershell works with any kind of slashes. Which version of make are you using?

I have a couple of suggestions:
- _make_ does not like whitespace in variable values, please replace _Program Files (x86)_ with something not containing whitespace or include the toolchain bin folder in PATH and use just relative names like _avr-gcc.exe_
- replace all the ```mkdir -p $(@D)``` with ```mkdir -p $(subst /,\,$(@D))```

Could you please check and tell me if this fixes the build for you?

Thanks!

**Comment by BdT141** [comment]
Hi Alex,

I'm using the Win10 native PowerShell version 5.1.19041.906.
Thanks a lot for the reply. I agree that the main problem was the blank space in the compiler path. `subst` did help up until the makefile tried to run the avr-size command and then it failed again. Adding the compiler bin folder to PATH solved the problem.

Just two things I noticed that may be a windows PS issue. It seems windows PS doesn't recognise the `-f` in `rm -f` that the make variable `RM` resolves to so what I did was I redefined `RM= rm -Force` so it works with my PS. Also when you add `-p` to the `mkdir` command it creates a folder called "-p" in the project base folder. So what ended up happening was my folder structure looked like this:

ProjName/
__________main.cpp
__________-p/
__________.vscode/
__________________avr.build/

Removing the `-p` fixes it, but here you do need the `subs` for it to understand the path.

**Comment by Alex079** [comment]
I think a dedicated ```avr.targets.mk``` template file is needed for Windows. Thank you for the investigation!
I will try to update soon.

**Comment by BdT141** [comment]
Thanks a lot, I look forward to using the windows template soon. For the cleaning section I used this 
`clean :`
`$(info Cleaning)`
`rmdir /s/q $(subst /,\,$(A.output.dir))`
`$(info   )`

It seems windows' version of rm is rmdir.

**Comment by Alex079** [comment]
released v2
