### ISSUE TITLE
Error Building 

### ISSUE THREAD

**Issue by iRBugSplat** [Alex079/vscode-avr-helper#16]
Hi,

I have a problem with building. My terminal shows this error.

> Executing task in folder Workspace: make -fe:\Workspace\.vscode\avr.targets.mk build <

make: *** No rule to make target '.vscode/avr.build/obj/main.C.o', needed by '.vscode/avr.build/output.elf'.  Stop.
The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command make -fe:\Workspace\.vscode\avr.targets.mk build" terminated with exit code: 1.

Do you have any suggestions on what I did wrong?

Cheers
Yannick

**Comment by Alex079** [comment]
Hi!

One possible workaround is to try the Makefile from here https://raw.githubusercontent.com/Alex079/vscode-avr-helper/7d3a18e31cb2d8e802e6fe0fd27c918f30ab36ed/resources/windows/avr.targets.mk
Make a backup and replace your `avr.targets.mk` with this file.

I plan to stop using `make` for builds. You can try the preview version from this branch https://github.com/Alex079/vscode-avr-helper/tree/windows_10_make but it is not yet complete. If you have `node`, `npm` and `yarn` installed, you can package the extension yourself by running `npx vsce package` and then install it from resulting `.vsix` file.

Regards,
Alex

**Comment by iRBugSplat** [comment]
Thanks,

the new Makefile works well. The errors with the already existing subdirectory need to be ingnored I think.
