### ISSUE TITLE
Visual Studio initial setup on windows 10 Error

### ISSUE THREAD

**Issue by MazenATaha** [Alex079/vscode-avr-helper#21]
Hello, 
I faced problem when I used initial setup command after I installed the plug in.
steps I took:
  1- Installed all the requirements first.
  2-Installed the Plugin.
  3-Run command AVR Helper Preform initial setup.
Attached a screen shoot.

![image](https://user-images.githubusercontent.com/26487763/139578660-0b77c2ce-22b0-4f79-9062-e04ebcc54fd3.png)

**Comment by Alex079** [comment]
Hello!
I need more details about the problem. Was the `.vscode` subfolder created? Which versions of VSCode and extension are you using?

**Comment by MazenATaha** [comment]
Dear Alex, 
 Thanks for the quick replay.
 I have fixed it and forget to close & delete the issue.  had linked VScode opened on another Laptop same time. Thus, restarting didn't take effect till I was home. (noob me XD) 
I am not sure What cause the issue at first place. but on my Work Laptop it worked from first time.

Although I didn't use the tool as Wanted due to compiler error. Despite, the same code on different IDE compile and generate .HEX & .elf without problem.
 
 I will tinker with it in the following days. Hoping I could make a guide for people (beginners) like me Who wanna use VScode for AVRs with no experience in compiling and build process.
Thanks for the Plugin it is too straight forward and I like it.

**Comment by Alex079** [comment]
OK, good news! Currently the support for Windows needs improvement. I am working on it and build improvement overall, and it would be great to get some feedback about the preview build https://github.com/Alex079/vscode-avr-helper/files/7307182/vscode-avr-helper-0.0.0-preview.zip 
Thank you!

**Comment by MazenATaha** [comment]
I tried it today. However, it didn't update the path and I had to update it manual using "Edit configure" myself.
I am doing a clean reinstall of VScode and only install C/C++ intellisense extension afterward and will report my finding.

I will close this issue for now. Contact you directly next time.
