### ISSUE TITLE
main.c vs main.C

### ISSUE THREAD

**Issue by arjepsen** [Alex079/vscode-avr-helper#22]
Hey.
I'm trying to use the extension, but I'm running into some issues (using it on windows10)

I have a very simple main.c file that I'm trying to build.
But I get:

`make: *** No rule to make target '.vscode/avr.build/obj/src/main.C.o', needed by '.vscode/avr.build/output.elf'.  Stop.
The terminal process "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command make -fc:\Users\Anders\Documents\vscode-atmega2560\NyTest\.vscode\avr.targets.mk build" terminated with exit code: 1.`

I think it's something in the script, 'cause if I change the file name from main.c to mainC (capital C), I get one step further:

I belive it's something in the F.dep functions - but I haven't been able to narrow it down yet.

**Comment by Alex079** [comment]
Hello!
Thanks for the bug report. I will test this case with the next plugin version. Hopefully, there will be no issue :)
Regarding the `-D` flags, this sounds like a good new feature. Can you please tell what is the use case? Is this flag supposed to be selected manually right before flashing?

**Comment by arjepsen** [comment]
Here's a screenshot of the result, when I try to flash:
[image: image.png]

If I understand correctly, the -D flag disables the erase of the flash,
which seems is unnecessary on the atmega2560.
If I use the exact same command line, but with the -D flag, everything is
fine.
It would be awesome, if the extension had the option to leet the user
customize the avrdude flags. :-)

It's already a really nice and handy extension though - I quite like it.
Like I mentioned, the other issue I had, was with the F.dep functions in
the makefile, that ended up returning main.c AND main.C, so I had to remove
the last part of those two funtions.

Regards.
Anders

**Comment by Alex079** [comment]
Hello,

The next release will not be using `make`, and this kind of build problem will be gone.

I do not see right now a good and simple UI design for `avrdude` flags.
These flags could go into extension settings and be set as needed, but then this makes it harder to change flags for one particular flashing session.
Plain text input before flashing could be challenging to parse correctly.
Another way is to gradually add new flags into the checklist input before flashing, but then this checklist may grow a lot and become annoying at some point.
Yet another way to do it is to let the user configure flags scope: i.e. certain flags are to be selected every time before flashing, others can be set once and used for flashing without prompt.
I would appreciate your opinion about this feature.

Regards.
Alex

**Comment by arjepsen** [comment]
I think the avrdude flags wont change much - at least not for me :-)
I will usually work on the same device, hooked up to the same usb port.
I think for me, the best option would be to have a field available in the
extension settings, were I could enter the all flags I prefer - maybe with
some initial standards already entered?
Anyways, that's just how I see it - YMMW :-)

Regards
Anders

**Comment by Alex079** [comment]
released v2
