### ISSUE TITLE
No hex file on build command

### ISSUE THREAD

**Issue by cosphi84** [Alex079/vscode-avr-helper#25]
there is no .hex file generated during build target.

it is done with run command : 
`avr-objcopy -O ihex main.c.o main.hex` 

manually on terminal, but it will perfect to including this command in the avr.targets.mk

**Comment by Alex079** [comment]
Thank you for suggestion!
I can add this as a configuration option (there is no more avr.targets.mk) in the next next version.
I think it can be something similar to `avr-objcopy -O ihex -j .text -j .data output.elf output.hex` executed post-build, just to make sure that the dump will contain all linked code.
