### ISSUE TITLE
Able to Specify Build File Path

### ISSUE THREAD

**Issue by YuLun-bili** [Alex079/vscode-avr-helper#30]
For now this extension would build all files under parent folder, therefore the extension won't run perfectly under following cases:
- opened a folder contains several different main files for different projects
- opened the parent folder contains different project sub-folders

So my idea is add an optional parameter before building, if not given then build all files in parent folder

**Comment by Alex079** [comment]
Is it possible to use VSCode Workspace in this case?

**Comment by YuLun-bili** [comment]
It's indeed possible, we can isolate each project. Only small issue is I need to setup again when I have a new project.
