### ISSUE TITLE
An option to see the avr-gcc command being executed

### ISSUE THREAD

**Issue by marcinjahn** [Alex079/vscode-avr-helper#38]
I wish I could see the full command that the extension invokes to run avr-gcc.
The extension shows avrdude's command, so it would makse sense to also show how avr-gcc is invoked.

**Comment by eyalabraham** [comment]
Just an observation, the developer has these logs displayed by VSCode in developer tools ( Help > Toggle Developer Tools > Console) an noted [here](https://github.com/Alex079/vscode-avr-helper/discussions/34#discussioncomment-4373529).

**Comment by marcinjahn** [comment]
Thanks! That's great that I can see that already. However, opening Chromium Dev Console is a bit weird. It would be nice if avr-helper could log to some "normal" output in VS Code.

**Comment by Alex079** [comment]
Hello!

I can see the following ways to implement it:
- a dedicated output channel for logs (in `View`>`Output` panel)
- echo commands directly in the task output terminal (I prefer this one, to be honest)

What do you think would be the better way to display the commands?

**Comment by marcinjahn** [comment]
Hi @Alex079, I also think the second option is alright, I guess that's how the avrdude output is implemented.

**Comment by Alex079** [comment]
#40 still needs some testing

**Comment by Alex079** [comment]
published v2.2.0
