### ISSUE TITLE
Configured avr-gcc parameters are not being applied

### ISSUE THREAD

**Issue by marcinjahn** [Alex079/vscode-avr-helper#39]
Here's my configuration:

![image](https://user-images.githubusercontent.com/10273406/209226504-1cbf70c1-8708-4001-b8f7-e6580d9f80bf.png)

Here's what gets executed:

![image](https://user-images.githubusercontent.com/10273406/209226533-7f8d3401-1c03-47cf-8cbf-6fba4e236e33.png)

Some of the configured parametes (like `-DENABLE_CONSOLE`) are not being used when avr-gcc is invoked. Why is that?

**Comment by Alex079** [comment]
Hello!
It looks like in your build you already have .obj files with timestamp later than that of your .cpp files. In this case the compilation is skipped.
You can do "clean" "build" to force recompilation.

**Comment by marcinjahn** [comment]
You were right! Thanks for the advice.
