### ISSUE TITLE
Move build results directory to the top level of the project filesystem

### ISSUE THREAD

**Issue by leonty** [Alex079/vscode-avr-helper#42]
The default build output is a little bit strange, why so deep and so hidden? ) Many other build systems (like maven, gradle, cmake) use a directory at the top level of the project and there are reasons, the output results can be used beyond the build process and so they are easily accessible. Maybe it's reasonable to move the build folder out of .vscode folder, assuming that obj/elf build results have nothin common with vscode?

> attiny10_garland % find .
> .
> ./.vscode
> ./.vscode/.DS_Store
> ./.vscode/settings.json
> ./.vscode/c_cpp_properties.json
> ./.vscode/avr.build
> ./.vscode/avr.build/obj
> ./.vscode/avr.build/obj/Users
> ./.vscode/avr.build/obj/Users/leonty
> ./.vscode/avr.build/obj/Users/leonty/Projects
> ./.vscode/avr.build/obj/Users/leonty/Projects/attiny10_garland
> ./.vscode/avr.build/obj/Users/leonty/Projects/attiny10_garland/main.cpp.obj
> ./.vscode/avr.build/output.elf
> ./main.cpp

**Comment by Alex079** [comment]
Sounds like a good idea! Do we need the build output folder name to be configurable or just name it "build"?

**Comment by leonty** [comment]
As to me, just using unconditionally <project_root>/build is good enough.

**Comment by Alex079** [comment]
published v2.2.0
