### ISSUE TITLE
Default flash area

### ISSUE THREAD

**Issue by Alex079** [Alex079/vscode-avr-helper#43]
Select flash memory area by default

**Comment by leonty** [comment]
That is indeed a useful feature. But I'd offer even more - when clicking on "flash" start programming immediately with flash memory area selected by default. And only, say, having CTRL or ALT pressed at the same time show the enhanced flash menu. Same for the build process.
Recently I was debugging an attiny10 project  and that's exactly what consumed time - click "build" at the bottom of the display, move cursor to the menu on the top of display, click "build" again, move cursor to the bottom, click "flash", move cursor to the top, click "flash, ok" etc.
ESP32 extension offers, for example, single "build and flash" button which is very useful and demands no other actions.

**Comment by Alex079** [comment]
This feature was requested from the Marketplace page. I did both: added a new shortcut command and selected "flash" area by default when using "Flash" command. I still need to retest error handling before release.
In the meantime, to speed up your example workflow, one could use `Ctrl` `Shift` `P` to open the command list instead of clicking status bar items.

Feel free to suggest a good name for the new command and the new status bar item.

**Comment by leonty** [comment]
ESP-IDF has just an icon for this action:
![image](https://user-images.githubusercontent.com/1595354/216780644-fccde67c-20db-4235-8554-16a4d991bf93.png)

**Comment by Alex079** [comment]
published v2.2.0
