### ISSUE TITLE
Options  "-ffunction-sections", "-fdata-sections" are for compiler, not linker

### ISSUE THREAD

**Issue by leonty** [Alex079/vscode-avr-helper#48]
The options "-ffunction-sections", "-fdata-sections" should be used in compiler calls, not linker. 
https://gcc.gnu.org/onlinedocs/gnat_ugn/Compilation-options.html

The linker needs "-Wl,-gc-sections" instead to perform dead code elimination.

**Comment by Alex079** [comment]
Thanks for the hint! I will check this week. I guess only default values need to be changed.
